/****** Object:  Table [FDP_APPLICATION].[ANNUITY_APPLICATION]    Script Date: 1/8/2026 6:40:45 PM ******/

 

DECLARE @sql NVARCHAR(1000);

--Drop constraints if exists

IF EXISTS (

    SELECT * 

    FROM sys.objects 

    WHERE name = 'PK_ANNUITY_APPLICATION' AND type IN ('PK')

)

BEGIN

    SET @sql = 'ALTER TABLE [FDP_APPLICATION].[ANNUITY_APPLICATION] DROP CONSTRAINT PK_ANNUITY_APPLICATION;';

    EXEC sp_executesql @sql;

 

END

--drop temp table if exists & create

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[FDP_APPLICATION].[ANNUITY_APPLICATION_TMP]') AND type in (N'U'))

DROP TABLE [FDP_APPLICATION].[ANNUITY_APPLICATION_TMP]

 

SET ANSI_NULLS ON

GO

 

SET QUOTED_IDENTIFIER ON

GO

 

CREATE TABLE [FDP_APPLICATION].[ANNUITY_APPLICATION_TMP]

(

    [APPLICATION_DIRECTORY_ID] [bigint] NOT NULL,

    [PRODUCT_DIRECTORY_ID] [bigint] NOT NULL,

    [APPLICATION_ID] [varchar](50) NOT NULL,

    [APPLICATION_SEQUENCE_ID] [int] NULL,

    [POLICY_NUMBER] [varchar](50) NULL,

    [SOURCE_PRODUCT_CODE] [varchar](20) NULL,

    [ADVISORY_PRODUCT_INDICATOR] [char](1) NOT NULL,

    [PRODUCT_CODE] [varchar](20) NULL,

    [PRODUCT_SOURCE_SYSTEM_CODE] [varchar](20) NULL,

    [LINE_OF_BUSINESS_CODE] [varchar](20) NULL,

    [LINE_OF_BUSINESS_TYPE_CODE] [varchar](20) NULL,

    [PRODUCT_NAME] [nvarchar](150) NULL,

    [PLAN_CODE] [varchar](20) NULL,

    [PLAN_NAME] [varchar](150) NULL,

    [PRODUCT_GROUP_NAME] [varchar](150) NULL,

    [PRODUCT_CATEGORY_NAME] [varchar](150) NULL,

    [CARRIER_COMPANY_NAME] [varchar](150) NULL,

    [CUSIP_NUMBER] [varchar](100) NULL,

    [PRODUCT_START_DATE] [datetime2](7) NULL,

    [PRODUCT_END_DATE] [datetime2](7) NULL,

    [SOURCE_APPLICATION_STATUS_CODE] [varchar](20) NULL,

    [SOURCE_APPLICATION_STATUS_DESCRIPTION] [varchar](1024) NULL,

    [ENTERPRISE_APPLICATION_STATUS_CODE] [varchar](20) NULL,

    [ENTERPRISE_APPLICATION_STATUS_DESCRIPTION] [varchar](1024) NULL,

    [ACORD_APPLICATION_STATUS_CODE] [varchar](20) NULL,

    [ACORD_APPLICATION_STATUS_DESCRIPTION] [varchar](1024) NULL,

    [APPLICATION_RECEIVED_DATE] [datetime2](7) NULL,

    [APPLICATION_SUBMITTED_DATE] [datetime2](7) NULL,

    [APPLICATION_SIGNED_DATE] [datetime2](7) NULL,

    [INITIAL_EXPECTED_PREMIUM_AMOUNT] [decimal](18, 2) NULL,

    [FINAL_EXPECTED_PREMIUM_AMOUNT] [decimal](18, 2) NULL,

    [TOTAL_EXPECTED_PREMIUM_AMOUNT] [decimal](38, 16) NULL,

    [CASH_WITH_APPLICATION_AMOUNT] [decimal](38, 16) NULL,

    [REQUESTED_PREMIUM_AMOUNT] [decimal](38, 16) NULL,

    [EXCHANGE_EXPECTED_AMOUNT] [decimal](38, 16) NULL,

    [EXCHANGE_REPLACEMENT_INDICATOR] [char](1) NULL,

    [PRODUCER_ORDERED_FUND_ESTIMATED_AMOUNT] [decimal](38, 16) NULL,

    [SOURCE_APPLICATION_SIGNED_STATE_CODE] [varchar](20) NULL,

    [SOURCE_APPLICATION_SIGNED_STATE_DESCRIPTION] [varchar](1024) NULL,

    [ENTERPRISE_APPLICATION_SIGNED_STATE_CODE] [varchar](20) NULL,

    [ENTERPRISE_APPLICATION_SIGNED_STATE_DESCRIPTION] [varchar](1024) NULL,

    [ACORD_APPLICATION_SIGNED_STATE_CODE] [varchar](20) NULL,

    [ACORD_APPLICATION_SIGNED_STATE_DESCRIPTION] [varchar](1024) NULL,

    [SOURCE_TAX_QUALIFIED_TYPE_CODE] [varchar](20) NULL,

    [SOURCE_TAX_QUALIFIED_TYPE_DESCRIPTION] [varchar](1024) NULL,

    [ENTERPRISE_TAX_QUALIFIED_TYPE_CODE] [varchar](20) NULL,

    [ENTERPRISE_TAX_QUALIFIED_TYPE_DESCRIPTION] [varchar](1024) NULL,

    [ACORD_TAX_QUALIFIED_TYPE_CODE] [varchar](20) NULL,

    [ACORD_TAX_QUALIFIED_TYPE_DESCRIPTION] [varchar](1024) NULL,

    [SOURCE_COMMISSION_OPTION_TYPE_CODE] [varchar](20) NULL,

    [SOURCE_COMMISSION_OPTION_TYPE_DESCRIPTION] [varchar](1024) NULL,

    [ENTERPRISE_COMMISSION_OPTION_TYPE_CODE] [varchar](20) NULL,

    [ENTERPRISE_COMMISSION_OPTION_TYPE_DESCRIPTION] [varchar](1024) NULL,

    [ACORD_COMMISSION_OPTION_TYPE_CODE] [varchar](20) NULL,

    [ACORD_COMMISSION_OPTION_TYPE_DESCRIPTION] [varchar](1024) NULL,

    [SOURCE_FUND_RESTRICTION_CODE] [varchar](20) NULL,

    [SOURCE_FUND_RESTRICTION_DESCRIPTION] [varchar](1024) NULL,

    [ENTERPRISE_FUND_RESTRICTION_CODE] [varchar](20) NULL,

    [ENTERPRISE_FUND_RESTRICTION_DESCRIPTION] [varchar](1024) NULL,

    [ACORD_FUND_RESTRICTION_CODE] [varchar](20) NULL,

    [ACORD_FUND_RESTRICTION_DESCRIPTION] [varchar](1024) NULL,

    [SOURCE_INDEX_EFFECTIVE_DATE_OPTION_CODE] [varchar](20) NULL,

    [SOURCE_INDEX_EFFECTIVE_DATE_OPTION_DESCRIPTION] [varchar](1024) NULL,

    [ENTERPRISE_INDEX_EFFECTIVE_DATE_OPTION_CODE] [varchar](20) NULL,

    [ENTERPRISE_INDEX_EFFECTIVE_DATE_OPTION_DESCRIPTION] [varchar](1024) NULL,

    [ACORD_INDEX_EFFECTIVE_DATE_OPTION_CODE] [varchar](20) NULL,

    [ACORD_INDEX_EFFECTIVE_DATE_OPTION_DESCRIPTION] [varchar](1024) NULL,

    [PENDING_INDICATOR] [char](1) NULL,

    [ENTERPRISE_POLICY_STATUS_CODE] [varchar](20) NULL,

    [ENTERPRISE_POLICY_STATUS_DESCRIPTION] [varchar](1024) NULL,

    [EVENT_TS] [datetime2](7) NULL,

    [SRC_SYS_CD] [varchar](20) NOT NULL,

    [LOAD_ID] [int] NULL,

    [LAST_UPDATE_LOAD_ID] [int] NULL,

    [INSERT_TS] [datetime2](7) NULL,

    [UPDATE_TS] [datetime2](7) NULL,

 CONSTRAINT [PK_ANNUITY_APPLICATION] PRIMARY KEY NONCLUSTERED 

    (

        [APPLICATION_DIRECTORY_ID] ASC,

        [APPLICATION_ID] ASC

    ) NOT ENFORCED 

)

WITH

(

    DISTRIBUTION = HASH ( [APPLICATION_DIRECTORY_ID] ),

    CLUSTERED COLUMNSTORE INDEX

)

GO